# Generated by Django 2.2.3 on 2019-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190725_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoboard',
            name='photo1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
