# Generated by Django 2.2.3 on 2019-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190729_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='photo1',
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
