# Generated by Django 2.2.3 on 2019-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190729_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
